import "./globals.css";
import { Public_Sans } from "next/font/google";

const public_sans = Public_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${public_sans.className} bg-veryLightGray`}>{children}</body>
    </html>
  );
}
